App\Users\Domain\Dto\UserDto:
  properties:
    id:
      type: integer

    firstName:
      type: string

    lastName:
      type: string

    email:
      type: string

    phone:
      type: string