jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            application:
                namespace_prefix: "App\\Application\\Dto"
                path: '%kernel.project_dir%/src/Infrastructure/Deserializer/Mapping/Application/Dto'
