jms_serializer:
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            banking:
                namespace_prefix: "App\\Banking\\Application\\Dto"
                path: '%kernel.project_dir%/src/Banking/Infrastructure/Deserializer/Mapping/Application/Dto'

            users:
                namespace_prefix: "App\\Users\\Domain\\Dto"
                path: '%kernel.project_dir%/src/Users/Infrastructure/Deserializer/Mapping/Domain/Dto'
