App\Banking\Application\Dto\NewClientDto:
  exclusion_policy: ALL

  properties:
    name:
      type: string

    surname:
      type: string

    email:
      type: string

    bankAccounts:
      type: array<App\Banking\Application\Dto\NewBankAccountDto>