controllersBankingWeb:
    resource: ../src/Banking/Bridge/Controller/Web
    type: annotation

controllersBankingRest:
    resource: ../src/Banking/Bridge/Controller/Rest
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
